#!/bin/sh
# Copyright 2016, 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# skip verification if set on git config file
skip=$(git config --bool hooks.pylintskip)
if [ "$skip" == "true" ]; then
    exit 0
fi

# fetch list of files intended for commit
files=$(git diff-index --cached --name-only --diff-filter=AM HEAD)
tempfile=$(mktemp)
for file in $files; do
    # skip non python files
    echo $file | grep -q '^.*\.py$'
    if [ $? -ne 0 ]; then
        continue
    fi

    # execute pylint in a virtual env
    echo -n "Checking code guidelines on $file ... "
    tox -e lint -- $file &>>$tempfile
    if [ $? -ne 0 ]; then
        echo "[FAILED]"
        echo "Verification failed (see logfile $tempfile). Run pylint "\
"manually and fix the errors, or add 'git config --bool hooks.pylintskip "\
"true' to skip it (at your own RISK!)" >&2
        exit 1
    fi
    rm -f $tempfile
    echo "[OK]"
done
