variables:
  GIT_STRATEGY: clone
  REGISTRY: tessia-dev.domain.com:5000

stages:
  - prepare
  - build
  - unittests
  - clitests
  - push
  - cleanup

prepare:
  stage: prepare
  script:
    # make sure the deps from orc are met and up-to-date
    - pip3 install --user -U pip -rtools/ci/requirements.txt

build_cli:
  stage: build
  script:
    - tools/ci/orc build --image=tessia-cli

build_server:
  stage: build
  script:
    - tools/ci/orc build --image=tessia-server

unittests_server:
  stage: unittests
  script:
    - tools/ci/orc unittest --image=tessia-server

clitests:
  stage: clitests
  script:
    # variables are set by each runner
    - tools/ci/orc clitest --fieldtests=${TESSIA_FIELD_TESTS_DIR} --img-passwd-file=${TESSIA_IMG_PASSWD_FILE}

push:
  stage: push
  script:
    - tools/ci/orc push --registry=${REGISTRY}
    # keep registry size under control
    - tools/dregman clean ${REGISTRY} tessia-cli
    - tools/dregman clean ${REGISTRY} tessia-server
  only:
    - master

cleanup:
  stage: cleanup
  script:
    - tools/ci/orc cleanup
  when: always
