variables:
  GIT_STRATEGY: fetch
  REGISTRY: tessia-dev.domain.com:5000

stages:
  - prepare
  - build
  - unittests
  - clitests
  - push
  - cleanup

prepare:
  stage: prepare
  script:
    # make sure the deps from orc are met and up-to-date
    - pip3 install --user -U pip -rtools/ci/requirements.txt

build_cli:
  stage: build
  script:
    - tools/ci/orc build --image=tessia-cli

build_engine:
  stage: build
  script:
    - tools/ci/orc build --image=tessia-engine

unittests_engine:
  stage: unittests
  script:
    - tools/ci/orc unittest --image=tessia-engine

clitests:
  stage: clitests
  script:
    - tools/ci/orc clitest --fieldtests=/home/tessia-builder/field_tests --baselibfile=/home/tessia-builder/cfg/tessia_baselib.yaml

push:
  stage: push
  script:
    - tools/ci/orc push --registry=${REGISTRY}
    # keep registry size under control
    - tools/dregman clean ${REGISTRY} tessia-cli
    - tools/dregman clean ${REGISTRY} tessia-engine
  only:
    - master

cleanup:
  stage: cleanup
  script:
    - tools/ci/orc cleanup
  when: always
