variables:
  GIT_STRATEGY: clone

stages:
  - build
#  - deploy

build:
  stage: build
  script:
    # make sure the deps from orc are met and up-to-date
    - pip3 install --user -U pip -rtools/ci/requirements.txt
    # checkout to correct branch
    - git checkout -b ${CI_COMMIT_REF_NAME:=$CI_BUILD_REF_NAME}
    - tools/ci/orc build

# TODO: further configure for deployments
#deploy_review:
#  stage: deploy
#  script:
#    - tools/ci/orc deploy
#  environment:
#    name: review/$CI_COMMIT_REF_NAME
#    url: https://$CI_ENVIRONMENT_SLUG.example.com
#  only:
#    - branches
#  except:
#    master
#
#deploy_staging:
#  stage: deploy
#  script:
#    - echo "Deploy to staging server"
#  environment:
#    name: staging
#    url: https://staging.example.com
#  only:
#  - master
#
#deploy_release:
#  stage: deploy
#  script:
#    - echo "Deploy to production server"
#  environment:
#    name: production
#    url: https://example.com
#  when: manual
#  only:
#  - master
