language: python

python:
  - 3.8

services:
  - docker

# After updating to focal CI still uses docker-compose instead of 
# docker-compose-v2, installing it manually now
before_install:
  - sudo apt-get update
  - sudo apt-get -y install docker-compose-v2

# Seems that travis doesn't stop running scripts after the first one
# fails (see https://github.com/travis-ci/travis-ci/issues/1066) so
# a chain with '&&' was used.
script: |
  docker-compose --version &&
  tools/ci/orc build --image=tessia-cli &&
  tools/ci/orc build  --image=tessia-server &&
  tools/ci/orc unittest &&
  tools/ci/orc clitest

os: linux
dist: focal
