# directory where doc files are located
docs_dir: doc
# where to store output files
site_dir: ../build/html
# TODO: create tessia logo
#site_favicon: favicon.ico
# enable permalinks for each header
markdown_extensions:
    - toc:
        permalink: True
# css/html theme
theme: cerulean
site_name: tessia
repo_url: https://gitlab.com/tessia-project/tessia
copyright: IBM Corp.
pages:
- Home: 'index.md'
- Users:
    - Client installation: 'users/client_install.md'
    - Server installation: 'users/server_install.md'
    - Server configuration: 'users/server_conf.md'
    - Resources model: 'users/resources_model.md'
    - Getting started: 'users/getting_started.md'
    - Power Manager machine: 'users/powerman_machine.md'
    - Ansible machine: 'users/ansible_machine.md'
    - Permissions model: 'users/permissions_model.md'
    - Supported installation combinations: 'users/supported_install_combinations.md'
    - Howtos: 'users/howtos.md'
    - Project versioning scheme: 'users/versioning.md'
    - REST-like API: 'users/api.md'
    - Installing a kvm guest with fcp disk and macvtap interface: 'users/kvm_fcp_macvtap_install.md'
- Developers:
    - Coding guidelines: 'developers/coding_guidelines.md'
    - Development process: 'developers/dev_process.md'
    - How to setup a development environment: 'developers/dev_env.md'
    - Integration and unit tests: 'developers/tests.md'
    - Working with documentation: 'developers/documentation.md'
    - Continous Integration: 'developers/continuous_integration.md'
    - Design topics: 'developers/design.md'
