# directory where doc files are located
docs_dir: doc
# where to store output files
site_dir: ../build/html
# enable permalinks for each header
markdown_extensions:
    - toc:
        permalink: True
# css/html theme
theme: readthedocs
site_name: tessia
repo_url: https://gitlab.com/tessia-project/tessia
copyright: Copyright IBM Corp. 2016, 2017, 2018
pages:
- Home: 'index.md'
- Releases: 'releases.md'
- Users:
    - Client installation: 'users/client_install.md'
    - Server installation: 'users/server_install.md'
    - Server configuration: 'users/server_conf.md'
    - Getting started: 'users/getting_started.md'
    - Resources model: 'users/resources_model.md'
    - Autoinstall machine: 'users/autoinstall_machine.md'
    - Power Manager machine: 'users/powerman_machine.md'
    - Ansible machine: 'users/ansible_machine.md'
    - Supported installation combinations: 'users/supported_install_combinations.md'
    - Howtos: 'users/howtos.md'
    - Project versioning scheme: 'users/versioning.md'
    - REST-like API: 'users/api.md'
    - Installing a KVM guest with FCP disk and MACVTAP interface: 'users/kvm_fcp_macvtap_install.md'
    - Installing linux on zVM with DASD volumes and OSA interface: 'users/zvm_dasd_osa_install.md'
- Developers:
    - How to contribute (development process): 'developers/contributing.md'
    - Coding guidelines: 'developers/coding_guidelines.md'
    - How to setup a development environment: 'developers/dev_env.md'
    - Integration and unit tests: 'developers/tests.md'
    - Working with documentation: 'developers/documentation.md'
    - Continous Integration: 'developers/continuous_integration.md'
    - Design topics: 'developers/design.md'
    - Scheduler: 'developers/scheduler.md'
