# directory where doc files are located
docs_dir: doc
# where to store output files
site_dir: ../build/html
# TODO: create tessia logo
#site_favicon: favicon.ico
# enable permalinks for each header
markdown_extensions:
    - toc:
        permalink: True
# css/html theme
theme: cerulean
site_name: tessia
repo_url: https://gitlab.com/tessia-project/tessia-engine
#copyright: TBD
pages:
- Home: 'index.md'
- Users:
    - Resources model: 'users/resources_model.md'
    - Getting started: 'users/getting_started.md'
    - Howtos: 'users/howtos.md'
    - Project versioning scheme: 'users/versioning.md'
    - Client installation: 'users/client_install.md'
    - REST-like API: 'users/api.md'
    - Installing a kvm guest with fcp disk and macvtap interface: 'users/kvm_fcp_macvtap_install.md'
- Developers:
    - Coding guidelines: 'developers/coding_guidelines.md'
    - Development process: 'developers/dev_process.md'
    - How to get a server-side dev environment: 'developers/dev_env.md'
    - Unit tests: 'developers/unit_tests.md'
    - Integration tests/cmdline client tests: 'developers/client_tests.md'
    - Working with documentation: 'developers/documentation.md'
    - Continous Integration: 'developers/continuous_integration.md'
    - Design topics: 'developers/design.md'
