#!/usr/bin/env python3
# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Entry point to execute the testcases
"""

#
# IMPORTS
#
from tessia.cli.config import CONF
from util.static_executor import STATIC_DIR, StaticExecutor

import click
import os
import requests
import subprocess
import sys
import time

#
# CONSTANTS AND DEFINITIONS
#
CMD_COVERAGE = 'python3 -m coverage run -a --source=tessia.cli {}'
CMD_COVERAGE_ERASE = "python3 -m coverage erase"
CMD_COVERAGE_REPORT = "python3 -m coverage report -m"
CMD_WRAPPER = '-m wrapper {test_path} {api_url}'
MY_DIR = os.path.dirname(os.path.abspath(__file__))

#
# CODE
#
def _build_test_list(src_dir=None):
    """
    Create a dictionary containing all the testcases found in the corresponding
    folder.

    Args:
        src_dir (str): source directory containing test files, if None defaults
                       to STATIC_DIR

    Returns:
        dict: {'test_name': {'description': 'desc', 'path':
               '/path/to/test.yaml'}}
    """
    test_map = {}
    if src_dir:
        test_dir = src_dir
    else:
        test_dir = STATIC_DIR

    for entry in os.listdir(test_dir):
        if not entry.endswith('.yaml'):
            continue

        test_path = '{}/{}'.format(test_dir, entry)
        test_name = entry[:-5]
        testcase = StaticExecutor.load_testcase(test_path)
        test_map[test_name] = {
            'description': testcase['description'],
            'path': test_path
        }

    return test_map
# _build_test_list()

def _prepare_env():
    """
    Prepare a sane environment before running the tests.
    """
    home_dir = os.environ.get('HOME', None)
    if not home_dir:
        home_dir = '/tmp'
    os.environ['COVERAGE_FILE'] = '{}/.tessia.cli.coverage'.format(home_dir)
    os.chdir(MY_DIR)
# _prepare_env()

@click.command('exec')
@click.option(
    'names', '--name', multiple=True,
    help="testcase to execute; can be specified multiple times")
@click.option(
    'api_url', '--api-url', help="url where API is running")
@click.option(
    'src_dir', '--src',
    type=click.Path(exists=True, file_okay=False, resolve_path=True),
    help="dir containing test files, defaults to /static_testcases")
@click.option(
    'cleaner', '--cleaner', type=click.Path(exists=True, resolve_path=True),
    help="cleaner hook to use before each testcase")
@click.option(
    'cov_erase', '--cov-erase', type=click.BOOL, default=True,
    help="whether to erase previous collected coverage data (default yes)")
@click.option(
    'cov_report', '--cov-report', type=click.BOOL, default=True,
    help="whether to print coverage report at the end (default yes)")
def exec_(names, api_url, src_dir, cleaner, cov_erase, cov_report):
    """
    execute one or more testcases
    """
    avail_map = _build_test_list(src_dir=src_dir)

    # build the list of tests to execute
    if not names:
        run_map = avail_map
    else:
        run_map = {}
        for testcase in names:
            try:
                run_map[testcase] = avail_map[testcase]
            except KeyError:
                raise click.ClickException(
                    "unknown testcase '{}'".format(testcase))
    click.echo(
        '[init] testcases to execute: {}'.format(', '.join(run_map.keys()))
    )
    if not api_url:
        api_url = CONF.get_config().get('server_url')
        if not api_url:
            raise click.ClickException(
                'error: --api-url not specified and api url not found in '
                'config file.')
        click.echo(
            '[init] warning: --api-url not specified, defaulting to {} from '
            'config file.'.format(api_url))

    _prepare_env()
    if cov_erase:
        subprocess.run(CMD_COVERAGE_ERASE, shell=True, check=1)

    # run each testcase
    for test_name, test_entry in run_map.items():
        if cleaner is not None:
            click.echo("[pre-start] calling cleaner '{}'".format(cleaner))
            clean_status = subprocess.call(cleaner, shell=True)
            if clean_status != 0:
                raise click.ClickException(
                    'cleaner failed with exit code {}'.format(clean_status))
        # make sure connection is back, sometimes there is a delay
        timeout = time.time() + 30
        failed = True
        click.echo('[init] waiting for API server to come up (30 secs)')
        while time.time() < timeout:
            time.sleep(1.0)
            try:
                requests.head(api_url, verify=False)
            except requests.exceptions.HTTPError:
                pass
            except requests.exceptions.ConnectionError:
                continue
            except Exception:
                raise
            failed = False
            break
        if failed:
            raise click.ClickException('Timed out while waiting for server')

        # switch to parent dir to make sure paths are found
        exec_cmd = CMD_WRAPPER.format(
            test_path=test_entry['path'], api_url=api_url)
        cmd_str = CMD_COVERAGE.format(exec_cmd)

        click.echo('[exec] {}'.format(cmd_str))
        # execute and return exit code
        result = subprocess.run(
            cmd_str, shell=True, stderr=subprocess.STDOUT, check=0)
        if result.returncode != 0:
            click.echo(result.stdout)
            raise click.ClickException(
                "testcase '{}' failed with exit code {}".format(
                    test_name, result.returncode)
            )

        click.echo("finished testcase '{}'".format(test_name))

    if cov_report:
        subprocess.run(CMD_COVERAGE_REPORT, shell=True, check=1)
# exec_()

@click.command('list')
@click.option(
    'src_dir', '--src',
    type=click.Path(exists=True, file_okay=False, resolve_path=True),
    help="dir containing test files, defaults to /static_testcases")
@click.option('terse', '--terse', is_flag=True,
              help="display only the test names")
def list_(src_dir, terse):
    """
    list the available testcases
    """
    headers = ['Testcase', 'Description']
    rows = [
        (test, entry['description']) for test, entry in _build_test_list(
            src_dir=src_dir).items()
    ]

    if terse:
        for row in rows:
            click.echo(row[0])
        return

    # determine biggest width for each column
    cols_width = [(len(header) + 2) for header in headers]
    for row in rows:
        for i in range(0, len(row)):
            row_width = len(row[i]) + 2
            if row_width > cols_width[i]:
                cols_width[i] = row_width

    output_cols = []
    output_sep = []
    for i in range(0, len(headers)):
        output_cols.append(headers[i].center(cols_width[i]))
        sep = '-' * cols_width[i]
        output_sep.append(sep)
    output = '\n' + '|'.join(output_cols)
    output += '\n'
    output += '+'.join(output_sep)
    # print rows
    for row in rows:
        output_row = []
        for i in range(0, len(row)):
            output_value = ' {}'.format(row[i])
            output_row.append(output_value.ljust(cols_width[i]))

        output += '\n{}'.format('|'.join(output_row))
    click.echo(output)
# list_()

@click.command('erase')
def erase():
    """
    erase collected coverage data
    """
    _prepare_env()
    proc = subprocess.run(CMD_COVERAGE_ERASE, shell=True)
    sys.exit(proc.returncode)
# erase()

@click.command('report')
def report():
    """
    print current coverage report
    """
    _prepare_env()
    proc = subprocess.run(CMD_COVERAGE_REPORT, shell=True)
    sys.exit(proc.returncode)
# report()

@click.group()
def root():
    """
    Tessia cmdline client test runner
    """
    pass
# root()

def main():
    """
    Entry point, executes the root group.
    """
    root.add_command(erase)
    root.add_command(exec_)
    root.add_command(list_)
    root.add_command(report)
    root()
# main()

if __name__ == '__main__':
    main()
