# Copyright 2021 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""0.0.14 (os_hard_del)

Revision ID: 973ee45934d2
Revises: 23056fcccb9d
Create Date: 2021-04-13 19:50:56.630230

"""

# revision identifiers, used by Alembic.
revision = '973ee45934d2'
down_revision = '23056fcccb9d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_system_profiles_operating_system_id_operating_systems', 'system_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_system_profiles_operating_system_id_operating_systems'), 'system_profiles', 'operating_systems', ['operating_system_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_system_profiles_operating_system_id_operating_systems'), 'system_profiles', type_='foreignkey')
    op.create_foreign_key('fk_system_profiles_operating_system_id_operating_systems', 'system_profiles', 'operating_systems', ['operating_system_id'], ['id'])
    # ### end Alembic commands ###
