#!/usr/bin/env python3
# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Wrapper for 'pip3 install'. Due to the fact that pip copies this directory to
a temporary folder prior to calling setup.py it's not possible to use git
commands to determine version, therefore we create a plain file before calling
the actual 'pip3 install' command.
"""

#
# IMPORTS
#
from setup import gen_version
import os
import sys

#
# CONSTANTS AND DEFINITIONS
#
MY_DIR = os.path.dirname(os.path.abspath(__file__))

#
# CODE
#

if __name__ == '__main__':
    VERSION = gen_version()
    with open('{}/VERSION'.format(MY_DIR), 'w') as file_fd:
        file_fd.write(VERSION)

    os.execvp('pip3', ['pip3', 'install'] + sys.argv[1:])
