#!/usr/bin/env bash
# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server_url=${TESSIA_SERVER_URL:-https://server:5000}

function _set_url() {
    # set the api url in the global conf file
    echo "server_url: $server_url" > /etc/tessia-cli/config.yaml
}

# instance specific settings to config file
_set_url

trap "exit" TERM QUIT INT

echo "info: waiting forever... if you need a shell, use docker exec -ti {container_name} /bin/bash"
while true; do sleep 1; done
