#!/bin/bash -e
# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# simple script to handle cleaning of db and restart of daemons
# for use in testing/development environment

my_dir=$(realpath `dirname $0`)
pushd "$my_dir/.." &>/dev/null

function cleanup {
    deactivate
    popd &>/dev/null
}

trap cleanup EXIT
source .tox/devenv/bin/activate

tools/control_daemons stop
tessia-dbmanage reset -y
tessia-dbmanage init-db
tools/control_daemons start
