#!/bin/bash
# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# simple script to handle start/stop/restart of tessia daemons
# for use in development environment

my_dir=$(realpath `dirname $0`)
pushd "$my_dir/.." &>/dev/null

function cleanup {
    deactivate
    popd &>/dev/null
}

function daemons_status {
    sched_pid=$(pgrep tess-scheduler)
    api_pid=$(pgrep uwsgi | head -1)
    ret_code=0

    if [ -z "$sched_pid" ]; then
        sched_str="dead"
        ret_code=1
    else
        sched_str="running (pid $sched_pid)"
    fi
    if [ -z "$api_pid" ]; then
        api_str="dead"
        ret_code=1
    else
        api_str="running (pid $api_pid)"
    fi

    echo "uwsgi: $api_str"
    echo "tess-scheduler: $sched_str"
    exit $ret_code
}

function kill_daemons {
    while pgrep tess-scheduler &>/dev/null; do
        killall tess-scheduler || true
        sleep 0.5
    done
    while pgrep uwsgi &>/dev/null; do
        sudo killall uwsgi || true
        sleep 0.5
    done
}

trap cleanup EXIT
source .tox/devenv/bin/activate
if [ "$1" == "start" ]; then
    if ! pgrep tess-scheduler &>/dev/null; then
        nohup tess-scheduler &>/dev/null &
    fi
    if ! pgrep uwsgi &>/dev/null; then
        sudo nohup bash -c 'source .tox/devenv/bin/activate && uwsgi --yaml .tox/devenv/etc/tessia/uwsgi.yaml' &>/dev/null &
    fi
    sleep 1
    daemons_status
elif [ "$1" == "restart" ]; then
    kill_daemons
    nohup tess-scheduler &>/dev/null &
    sudo nohup bash -c 'source .tox/devenv/bin/activate && uwsgi --yaml .tox/devenv/etc/tessia/uwsgi.yaml' &>/dev/null &
    sleep 1
    daemons_status
elif [ "$1" == "stop" ]; then
    kill_daemons
elif [ "$1" == "status" ]; then
    daemons_status
else
    echo "error: invalid action or no action specified." >&2
    exit 1
fi

