# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pylint: disable=all
"""0.0.2 add repository, gateway to profile

Revision ID: 14e7934c17c8
Revises: 5959912cd07d
Create Date: 2017-02-21 20:07:06.759780

"""

# revision identifiers, used by Alembic.
revision = '14e7934c17c8'
down_revision = '5959912cd07d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # fill all rows with user system by default
    op.add_column('repositories', sa.Column('modifier_id', sa.Integer(), nullable=False, server_default='1'))
    # remove default statement
    op.alter_column('repositories', 'modifier_id', server_default=None)
    # since name is unique we need to use sql
    op.add_column('repositories', sa.Column('name', sa.String()))
    op.execute('UPDATE repositories SET name = id')
    # now set the final not null constraint
    op.alter_column('repositories', 'name', nullable=False)
    op.add_column('repositories', sa.Column('owner_id', sa.Integer(), nullable=False, server_default='1'))
    # remove default statement
    op.alter_column('repositories', 'owner_id', server_default=None)
    op.add_column('repositories', sa.Column('project_id', sa.Integer(), nullable=False, server_default='1'))
    # remove default statement
    op.alter_column('repositories', 'project_id', server_default=None)
    op.create_index(op.f('ix_repositories_modifier_id'), 'repositories', ['modifier_id'], unique=False)
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_repositories_project_id'), 'repositories', ['project_id'], unique=False)
    op.create_unique_constraint(op.f('uq_repositories_name'), 'repositories', ['name'])
    op.create_foreign_key(op.f('fk_repositories_project_id_projects'), 'repositories', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('fk_repositories_owner_id_users'), 'repositories', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('fk_repositories_modifier_id_users'), 'repositories', 'users', ['modifier_id'], ['id'])
    op.add_column('system_profiles', sa.Column('gateway_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_system_profiles_gateway_id_system_ifaces'), 'system_profiles', 'system_ifaces', ['gateway_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_system_profiles_gateway_id_system_ifaces'), 'system_profiles', type_='foreignkey')
    op.drop_column('system_profiles', 'gateway_id')
    op.drop_constraint(op.f('fk_repositories_modifier_id_users'), 'repositories', type_='foreignkey')
    op.drop_constraint(op.f('fk_repositories_owner_id_users'), 'repositories', type_='foreignkey')
    op.drop_constraint(op.f('fk_repositories_project_id_projects'), 'repositories', type_='foreignkey')
    op.drop_constraint(op.f('uq_repositories_name'), 'repositories', type_='unique')
    op.drop_index(op.f('ix_repositories_project_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_modifier_id'), table_name='repositories')
    op.drop_column('repositories', 'project_id')
    op.drop_column('repositories', 'owner_id')
    op.drop_column('repositories', 'name')
    op.drop_column('repositories', 'modifier_id')
    op.drop_column('repositories', 'modified')
    op.drop_column('repositories', 'desc')
    # ### end Alembic commands ###
