# Copyright 2016, 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pylint: disable=all
"""0.0.1 (initial model)

Revision ID: 5959912cd07d
Revises: 
Create Date: 2017-02-08 10:45:01.348434

"""

# revision identifiers, used by Alembic.
revision = '5959912cd07d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_profiles_logical_volumes_profile_id_volume_id'), 'profiles_logical_volumes', ['profile_id', 'volume_id'])
    op.create_unique_constraint(op.f('uq_profiles_storage_volumes_profile_id_volume_id'), 'profiles_storage_volumes', ['profile_id', 'volume_id'])
    op.create_unique_constraint(op.f('uq_profiles_system_ifaces_profile_id_iface_id'), 'profiles_system_ifaces', ['profile_id', 'iface_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_profiles_system_ifaces_profile_id_iface_id'), 'profiles_system_ifaces', type_='unique')
    op.drop_constraint(op.f('uq_profiles_storage_volumes_profile_id_volume_id'), 'profiles_storage_volumes', type_='unique')
    op.drop_constraint(op.f('uq_profiles_logical_volumes_profile_id_volume_id'), 'profiles_logical_volumes', type_='unique')
    # ### end Alembic commands ###
